#include "RenderDocCaptureContext.h"

#include "util/StringUtils.h"

namespace jetbrains::renderdoc {
RenderDocCaptureContext::RenderDocCaptureContext(IReplayController *controller) {
  for (const auto &buf : controller->GetBuffers()) {
    buffers[buf.resourceId] = buf;
  }
  for (const auto &res : controller->GetResources()) {
    resources[res.resourceId] = res;
  }
}

const BufferDescription* RenderDocCaptureContext::try_get_buffer(ResourceId id) const {
  const auto it = buffers.find(id);
  return it != buffers.end() ? &it->second : nullptr;
}

const ResourceDescription* RenderDocCaptureContext::try_get_resource(ResourceId id) const {
  const auto it = resources.find(id);
  return it != resources.end() ? &it->second : nullptr;
}

std::wstring RenderDocCaptureContext::get_resource_name(ResourceId id) const {
  if (id == ResourceId::Null())
    return L"No Resource";

  if (const auto res = try_get_resource(id); res != nullptr) {
    return StringUtils::Utf8ToWide(res->name);
  }

  uint64_t num;
  memcpy(&num, &id, sizeof(num));
  return L"Unknown Resource " + std::to_wstring(num);
}

bool RenderDocCaptureContext::has_auto_generated_name(ResourceId id) const {
  if (id == ResourceId::Null())
    return true;

  if (const auto it = try_get_resource(id); it != nullptr)
    return it->autogeneratedName;

  return true;
}
}

